Update

diff --git a/Scripts/Openbox/usr-bin/kb-pipemenu b/Scripts/Openbox/usr-bin/kb-pipemenu
--- a/Scripts/Openbox/usr-bin/kb-pipemenu
+++ b/Scripts/Openbox/usr-bin/kb-pipemenu
@@ -9,18 +9,35 @@
 #================================================
 #================================================
 
+readonly KBSCRIPT="kb"
+readonly CFG_DIR="$HOME/.config/openbox"
+readonly RCPATH="$CFG_DIR/rc.xml"
+readonly KBTEXT="$CFG_DIR/kbinds.txt"
+readonly HELP='\tkb-pipemenu an Openbox Pipe Menu for displaying keybinds
+\tIt should normally be called from an openbox menu.
+\nOptions (usually passed from the menu):
+\t-h --help   show this message
+\t--keybinds  display keybindings defined in rc.xml as a menu
+\t(The keybinds in the menu are clickable, except for the Openbox
+\tcommands, which just exit the menu.)
+\t--rcedit    backup and edit rc.xml
+\nIf keyboard-pipemenu is called with no options (the usual method),
+it will output an xml openbox pipemenu for displaying keybindings.
+\tNOTE: Some of the functionality of this pipemenu depends on the script
+/usr/bin/kb which is provided by the package "scripts"'
+
 case "$@" in
     -h|--help) echo -e "$HELP" ; exit 0
 esac
 
 if ! . "/usr/lib/common/include.cfg" 2> /dev/null; then
-    echo $"Errore: Manca il file  /usr/lib/common/include.cfg" >&2
+    echo $"Errore: non trovo /usr/lib/common/include.cfg" >&2
     exit 1
 fi
 
 if ! type "$KBSCRIPT" &>/dev/null; then
     menuStart
-    menuSeparator "$KBSCRIPT non trovato.Installa gli script."
+    menuSeparator "$KBSCRIPT non esiste. Installa lo  scripts."
     menuEnd
     exit 1
 fi
@@ -34,7 +51,7 @@ if [[ $1 = '--rcedit' ]]; then
     elif hash xdg-open &>/dev/null; then
         xdg-open "$RCPATH"
     else
-        xterm -e "$EDITOR $RCPATH"
+        termite -e "$EDITOR $RCPATH"
     fi
     exit 0
 fi
@@ -42,7 +59,7 @@ fi
 if [[ $1 = '--keybinds' ]]; then
     "$KBSCRIPT" > /dev/null
     menuStart
-    menuSeparator "Openbox commandi"
+    menuSeparator "Finestra di comando Openbox"
     while read -r a b c; do
         if [[ "$a" = "o" ]]; then
             curItem=$(printf "%-20s %s" "$b" "$c")
@@ -51,7 +68,7 @@ if [[ $1 = '--keybinds' ]]; then
     done < "$KBTEXT"
 
     menuSeparator
-    menuSeparator "Esegui comandi"
+    menuSeparator "Esegui"
     while read -r a b c; do
         if [[ "$a" = "x" ]]; then
             curItem=$(printf "%-20s %s" "$b" "$c")
@@ -63,10 +80,10 @@ if [[ $1 = '--keybinds' ]]; then
 fi
 
 menuStart
-    menuItem "Edita (e crea backup)) rc.xml" "kb-pipemenu --rcedit"
+    menuItem "Crea un backup ed Edita rc.xml" "kb-pipemenu --rcedit"
     menuSeparator
-    menuItem "Visualizza le Shortcuts" "kb --gui"
-    echo '        <menu execute="kb-pipemenu --keybinds" id="Visualizza Shortcuts" label="Visualizza le Shortcuts in menu"/>'
+    menuItem "Visualizza le keybind in una finestra" "kb --gui"
+    echo '        <menu execute="kb-pipemenu --keybinds" id="Visualizza le keybind " label="Visualizza le keybind nel menu"/>'
 menuEnd
 
 exit 0
diff --git a/Scripts/Openbox/usr-bin/recent-files-pipemenu b/Scripts/Openbox/usr-bin/recent-files-pipemenu
--- a/Scripts/Openbox/usr-bin/recent-files-pipemenu
+++ b/Scripts/Openbox/usr-bin/recent-files-pipemenu
@@ -16,9 +16,9 @@ elif [ -r "${HOME}/.local/share/recently-used.xbel" ]; then
 elif [ -r "${HOME}/.recently-used.xbel" ]; then
     file_path="${HOME}/.recently-used.xbel"
 else
-    echo "$0: non trovo il file recently-used.xbel" >&2
+    echo "$0: cannot find a readable recently-used.xbel file" >&2
     echo '<openbox_pipe_menu>
-<separator label="Nessun file recently-used.xbel trovato." />
+<separator label="No recently-used.xbel file found." />
 </openbox_pipe_menu>'
     exit 1
 fi
@@ -74,7 +74,7 @@ files=$(perl -MURI::Escape -e 'print uri_unescape($ARGV[0]);' "$files")
 output='<openbox_pipe_menu>
 '"$files"'
 <separator/>
-  <item label="Elimina  Files Recenti">
+  <item label="Clear Recent Files">
     <action name="Execute">
       <command>&apos;'"$0"'&apos; --clear</command>
     </action>
